# Generated by Django 5.0.1 on 2024-02-26 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=255)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condicao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('clima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clima')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WeatherHistory',
        ),
    ]
